apiVersion: v1
kind: Pod
metadata:
  name: devwebapp-through
  labels:
    app: devwebapp
spec:
  serviceAccountName: myapp-sa
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      env:
      - name: VAULT_ADDR
        value: "http://external-vault.default.svc.cluster.local:8200"
      # VAULT_TOKEN should be injected via secret or vault agent
