apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
spec:
  serviceAccountName: myapp-sa
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      env:
      - name: VAULT_ADDR
        value: "http://192.168.1.18:8200"
      # VAULT_TOKEN should be injected via secret or vault agent
      - name: VAULT_TOKEN
        value: myroot