apiVersion: v1
kind: Service
metadata:
  name: external-vault-bd
  namespace: postgres
  labels:
    app: external-vault-bd
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-vault-bd
  namespace: postgres
  labels:
    app: external-vault-bd
subsets:
  - addresses:
      - ip: 192.168.1.18
    ports:
      - port: 8200