apiVersion: v1
kind: Service
metadata:
  name: ecomove-svc-images
  namespace: development-ecomove
  labels:
    app: ecomove-svc-images
spec:
  type: ClusterIP
  ports:
    - name: backend
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: development-ecomove
