apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-init-first: "true"
        vault.hashicorp.com/role: "bd-vehicles"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/ecomove/bd-vehicles"
        vault.hashicorp.com/vault-address: "http://external-vault.development-ecomove.svc.cluster.local:8200" 
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/ecomove/bd-vehicles" -}}
          export POSTGRES_USER="{{ .Data.data.DB_USER }}"
          export POSTGRES_PASSWORD="{{ .Data.data.POSTGRES_PASSWORD }}"
          export POSTGRES_DB="{{ .Data.data.POSTGRES_DB }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-file-db: "db.env"
    spec:
      serviceAccountName: myapp-bd
      containers:
        - name: postgres
          image: postgres:16.3
          ports:
            - containerPort: 5432
          command: ["/bin/bash", "-c"]
          args:
            - |
              source /vault/secrets/db.env
              exec docker-entrypoint.sh postgres
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi