apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-posgrest
  namespace: database-posgrest
spec:
  serviceName: "database-posgrest"
  replicas: 1
  selector:
    matchLabels:
      app: database-posgrest
  template:
    metadata:
      labels:
        app: database-posgrest
    spec:
      containers:
        - name: database-posgrest
          image: postgres:16.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgrest-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrest-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgrest-secret
                  key: DB_NAME_ECO
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi