# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: database-posgrest
  namespace: database-posgrest
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432